<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php $post = $this->getPost() ?>
<div class="post-list-item">
	
	<?php echo $this->getBeforePostContentHtml() ?>

	<div class="post-entry entry<?php if ($post->getFeaturedImage()): ?> post-entry-with-image<?php endif; ?>">
		<?php if ($post->isViewableForVisitor()): ?>
			<?php if ($featuredImage = $post->getFeaturedImage()): ?>
				<div class="featured-image left">
					<a class="blog_hover_img" href="<?php echo $post->getPermalink() ?>" title="<?php echo $this->escapeHtml($post->getPostTitle()) ?>"><img src="<?php echo $featuredImage->getFullSizeImage() ?>" alt="<?php echo $this->escapeHtml($post->getPostTitle()) ?>"/></a>
					<a class="blog_hover_list" href="<?php echo $post->getPermalink() ?>"><?php echo __('LEGGI L’ARTICOLO') ?></a>
				</div>
			<?php endif; ?>
			<div class="post_list_right">
				<span class="post-date when time">
					<i class="fa fa-calendar" aria-hidden="true"></i>
					<?php $string = $post->getPostDate();
					$timestamp = strtotime($string);
					 ?>
					<span class="day"><?php echo date("d", $timestamp); ?></span>
					<span class="month"><?php echo date("M", $timestamp); ?></span>
				</span>
				<h2><a href="<?php echo $post->getPermalink() ?>" title="<?php echo $this->escapeHtml($post->getPostTitle()) ?>"><?php echo $this->escapeHtml($post->getPostTitle()) ?></a></h2>
				<?php if ($this->displayExcerptInFeed() || $post->hasMoreTag()): ?>
					<?php 
						/**
						* You can pass the number of words you want the excerpt to be shortened to like so
						* The below code will only show the first 50 words of the excerpt
						* <?php echo $post->getPostExcerpt(50) ?>
						*
						**/ 
					?>
					<?php echo $post->getPostExcerpt(50) ?>

				<?php else: ?>

				<?php $productName = $this->htmlEscape(strip_tags($post->getPostContent(), array('p', 'strong', 'em')));?>
				<?php if (strlen(strip_tags($productName)) > 700) : ?>
					<?php echo Mage::helper('core/string')->truncate($productName, $length = 400, $etc = '...', $remainder = '', $breakWords = true) ?>
					<?php else : ?>
						<?php echo Mage::helper('core/string')->truncate($productName, $length = 200, $etc = '...', $remainder = '', $breakWords = true) ?>
				<?php endif ?>
				<a href="<?php echo $post->getPermalink() ?>" class="readmore"><?php echo __('LEGGI') ?></a>
				<?php endif; ?>
			</div>
		<?php else: ?>
			<?php echo $this->getPasswordProtectHtml($post) ?>
		<?php endif; ?>
	</div>
	<?php echo $this->getAfterPostContentHtml() ?>

</div>