<?php $posts = Mage::getResourceModel('wordpress/post_collection')
->addPostTypeFilter('post')
->setOrderByPostDate()
->addIsViewableFilter()
->setPageSize(20)
->load(); ?>
<div class="home_blog">
	<h1><?php echo __('Ultime dal blog') ?></h1>
	<?php if (count($posts) > 0): ?>
		<ul id="post-list" class="slick_home carousel">
			<?php foreach($posts as $post): ?>
				<li class="item">
					<div class="left_blog">
						<span class="post-date when time">
							<i class="fa fa-calendar" aria-hidden="true"></i>
							<span class="day"><?php echo $post->getPostDate('d'); ?></span> 
							<span class="month"><?php echo $post->getPostDate('M'); ?></span>
						</span>
					</div>
					<div class="right_blog">
						<h4><a href="<?php echo $post->getPermalink() ?>"><?php echo $this->escapeHtml($post->getPostTitle()) ?></a></h4>
						<?php $productName = $this->htmlEscape(strip_tags($post->getPostContent(), array('p', 'strong', 'em')));?>
						<?php if (strlen(strip_tags($productName)) > 700) : ?>
							<?php echo Mage::helper('core/string')->truncate($productName, $length = 350, $etc = '...', $remainder = '', $breakWords = true) ?>
						<?php else : ?>
							<?php echo Mage::helper('core/string')->truncate($productName, $length = 120, $etc = '...', $remainder = '', $breakWords = true) ?>
						<?php endif ?>
						<a href="<?php echo $post->getPermalink() ?>" class="readmore"><?php echo __('LEGGI') ?></a>
					</div>
				</li>
			<?php endforeach; ?>
		</ul>
	<?php endif; ?>
	<a href=" <?php echo Mage::getBaseUrl() ?>blog" class="vedi"><?php echo __('Vedi tutte') ?></a>
</div>
<script>
	jQuery('.slick_home').slick({
		dots: false,
		nav: true,
		nextArrow: '<i class="fa fa-chevron-circle-right" aria-hidden="true"></i>',
		prevArrow: '<i class="fa fa-chevron-circle-left" aria-hidden="true"></i>',
		slidesPerRow: 2,
		rows: 2
	});
</script>
<!-- <script>
	var scroll = new SmoothScroll('a[href*="#"]');
</script> -->




