<?php /*
<div class="page-title category-title">
<?php
    $_category = Mage::registry('current_category');
    if($_category->getLevel()==2){
        $sub_categorys = Mage::getModel('catalog/category')->load($_category->getId())->getChildrenCategories();
        echo "<h1>".$_category->getName()."</h1>";
    }elseif($_category->getLevel()==3){
        $sub_categorys = Mage::getModel('catalog/category')->load(Mage::registry('current_category')->getParentCategory()->getId())->getChildrenCategories();
        echo "<h1>".Mage::registry('current_category')->getParentCategory()->getName()."</h1>";
    }
?>
</div>
*/ ?>